### PR TITLE
Added support for `shadow` (`box-shadow` and `text-shadow)`

### LINKED ISSUE #26: Support `.shadow(color:radius:x:y)` (CSS)
Right now `view.shadow` doesn't support

### PR DESCRIPTION
**Pull request by 343max**
I have no idea what I'm doing here.

Trying to resolve #26

### CODE REVIEW

**Comment by helje5** [comment]
Want to make the extra step and implement changes? :-) It's really easy, checkout: https://github.com/swiftwebui/SwiftWebUI/blob/develop/Sources/SwiftWebUI/VirtualDOM/Layout/HTMLPaddingNode.swift

**Comment by 343max** [comment]
Done.

This project could really use some tests. :)

**Comment by helje5** [comment]
Test PRs welcome! :-) (I actually have quite a few tests in my private repo used during development, but I'm not sure the API is stable enough to make it worthwhile).

**Comment by helje5** [comment]
Hm, I suppose we should differentiate and join HTML nodes which affect the visuals vs those which affect the layout. E.g. ".background().shadow()" should probably be merged into a single div, while something like "padding" should break it up.

For this:
```swift
      Text("🥑🍞")
        .padding(.all)
        .background(.green, cornerRadius: 12)
        .shadow(color: .lightGray, radius: 5, x: 2, y: 2)
```
we currently get:
Screen Shot 2019-07-26 at 15 42 21

**Comment by 343max** [comment]
Yeah, I noticed exactly the same thing. :)

**Comment by helje5** [comment]
I've created https://github.com/swiftwebui/SwiftWebUI/issues/42

**Pull request merged**
